# Generated by Django 3.2.3 on 2021-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='confirm_account_number',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
    ]
