# Generated by Django 3.2.3 on 2021-06-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_transactions_confirm_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='confirm_account_number',
        ),
    ]
